export const siteConfig = {
  name: "GalvanoTrack",
  url: "https://galvanotrack.de",
  appUrl: "https://app.galvanotrack.de",
  description:
    "GalvanoTrack: Digitaler Laufzettel mit QR-Code für Galvanik-Betriebe. ISO 9001 & IATF 16949 konforme Dokumentation. Rückverfolgbarkeit auf Knopfdruck – kostenlos testen.",
  shortDescription: "Digitaler Laufzettel für Galvanik & Oberflächentechnik",
  keywords: [
    "Galvanik Software",
    "digitaler Laufzettel",
    "Rückverfolgbarkeit",
    "Oberflächentechnik",
    "Lohnbeschichter",
    "ISO Rückverfolgbarkeit",
    "IATF 16949",
    "QR-Code Galvanik",
    "Batch-Verfolgung",
    "Galvanik Dokumentation",
    "ISO 9001 Galvanik",
    "Galvanik Digitalisierung",
    "Chargenrückverfolgung",
    "Automotive Galvanik",
    "Lohnbeschichtung Software",
  ],
  authors: [{ name: "GalvanoTrack", url: "https://galvanotrack.de" }],
  creator: "GalvanoTrack",
  ogImage: "https://galvanotrack.de/og.png",
  locale: "de_DE",
  language: "de",
};
